# HopsWorks Kafka configuration

[hops]
url = '127.0.0.1'

# for testing only! set this flag to false or path to server certificate file
# needed when testing Hopsworks with a self signed certificate
# otherwise leave this true
verify = false

[project]
name =  'Kafka_Tutorial'
id = '1143'
ca_file = 'cert/trustStore.pem'
certificate_file = 'cert/keyStore.pem'
key_file = 'cert/keyStore.pem'
key_password = 'asdf123'

[kafka]
topic = 'temperature'
schema = 'sensor'
port = '9092'

[kafka.consumer]
group_id = 'TutorialGroup'
auto_offset_reset =  'earliest'

[api]
base = '/hopsworks-api/api'
key = 'K97n09yskcBuuFyO.scfQegUMhXfHg7v3Tpk8t6HIPUlmIP463BPdbTSdSEKAfo5AB8SIwY8LGgB4924B'
key_file = 'cert/apiKeyFile'
